import { Phrase } from "./components/App.contracts";

export const allSamples: Phrase[] = [
  /*
  { pinyin: 'yī', hieroglyph: '一', translate: 'один', lesson: 1 },
  { pinyin: 'èr', hieroglyph: '二', translate: 'два', lesson: 1 },
  { pinyin: 'sān', hieroglyph: '三', translate: 'три', lesson: 1 },
  { pinyin: 'sì', hieroglyph: '四', translate: 'четыре', lesson: 1 },
  { pinyin: 'wǔ', hieroglyph: '五', translate: 'пять', lesson: 1 },
  { pinyin: 'liù', hieroglyph: '六', translate: 'шесть', lesson: 1 },
  { pinyin: 'qī', hieroglyph: '七', translate: 'семь', lesson: 1 },
  { pinyin: 'bā', hieroglyph: '八', translate: 'восемь', lesson: 1 },
  { pinyin: 'jiǔ', hieroglyph: '九', translate: 'девять', lesson: 1 },
  { pinyin: 'shí', hieroglyph: '十', translate: 'десять', lesson: 1 },
  { pinyin: 'guó', hieroglyph: '国', translate: 'страна', lesson: 2 },
  { pinyin: 'xué', hieroglyph: '学', translate: 'учить', lesson: 2 },
  { pinyin: 'xí', hieroglyph: '习', translate: 'практиковать', lesson: 2 },
  { pinyin: 'hàn', hieroglyph: '汉', translate: 'хань', lesson: 2 },
  { pinyin: 'yǔ', hieroglyph: '语', translate: 'язык', lesson: 2 },
  { pinyin: 'wén', hieroglyph: '文', translate: 'письменность', lesson: 2 },
  { pinyin: 'xiě', hieroglyph: '写', translate: 'писать', lesson: 2 },
  { pinyin: 'zì', hieroglyph: '字', translate: 'иероглиф', lesson: 2 },
  { pinyin: 'nǚ', hieroglyph: '女', translate: 'женщина', lesson: 3 },
  { pinyin: 'zǐ', hieroglyph: '子', translate: 'сын', lesson: 3 },
  { pinyin: 'hǎo', hieroglyph: '好', translate: 'хорошо', lesson: 3 },
  { pinyin: 'shuǐ', hieroglyph: '水', translate: 'вода', lesson: 3 },
  { pinyin: 'mén', hieroglyph: '门', translate: 'дверь', lesson: 3 },
  { pinyin: 'wáng', hieroglyph: '王', translate: 'король', lesson: 3 },
  { pinyin: 'rì', hieroglyph: '日', translate: 'солнце', lesson: 4 },
  { pinyin: 'yuè', hieroglyph: '月', translate: 'месяц', lesson: 4 },
  { pinyin: 'mù', hieroglyph: '木', translate: 'дерево', lesson: 4 },
  { pinyin: 'mǎ', hieroglyph: '马', translate: 'лошадь', lesson: 4 },
  { pinyin: 'tián', hieroglyph: '田', translate: 'поле', lesson: 4 },
  { pinyin: 'tiān', hieroglyph: '天', translate: 'небо', lesson: 4 },
  { pinyin: 'míng', hieroglyph: '明', translate: 'светлый', lesson: 4 },
  { pinyin: 'lín', hieroglyph: '林', translate: 'лес', lesson: 4 },
  { pinyin: 'mā', hieroglyph: '妈', translate: 'мать', lesson: 4 },
  { pinyin: 'hé', hieroglyph: '河', translate: 'река', lesson: 4 },
  { pinyin: 'nín', hieroglyph: '您', translate: 'уважительное обращение', lesson: 5 },
  { pinyin: 'guì', hieroglyph: '贵', translate: 'дорогой', lesson: 5 },
  { pinyin: 'xìng', hieroglyph: '姓', translate: 'фамилия', lesson: 5 },
  { pinyin: 'wǒ', hieroglyph: '我', translate: 'я', lesson: 5 },
  { pinyin: 'ne', hieroglyph: '呢', translate: 'частица; выражает подчеркнутое утверждение', lesson: 5 },
  { pinyin: 'shì', hieroglyph: '是', translate: 'быть', lesson: 5 },
  { pinyin: 'ma', hieroglyph: '吗', translate: 'впросительная частица', lesson: 5 },
  { pinyin: 'bù', hieroglyph: '不', translate: 'нет', lesson: 5 },
  { pinyin: 'tóng', hieroglyph: '同', translate: 'вместе', lesson: 5 },
  { pinyin: 'lǎo', hieroglyph: '老', translate: 'старый', lesson: 6 },
  { pinyin: 'men', hieroglyph: '们', translate: 'суфф.множественного числа', lesson: 6 },
  { pinyin: 'shī', hieroglyph: '师', translate: 'учитель', lesson: 6 },
  { pinyin: 'jiào', hieroglyph: '叫', translate: 'называть', lesson: 6 },
  { pinyin: 'nǐ', hieroglyph: '你', translate: 'ты', lesson: 6 },
  { pinyin: 'shén me', hieroglyph: '什么', translate: 'что', lesson: 6 },
  { pinyin: 'míng', hieroglyph: '名', translate: 'имя', lesson: 6 },
  { pinyin: 'nǎ', hieroglyph: '哪', translate: 'который', lesson: 6 },
  { pinyin: 'yě', hieroglyph: '也', translate: 'тоже', lesson: 6 },
  { pinyin: 'shuō', hieroglyph: '说', translate: 'говорить', lesson: 6 },
  { pinyin: 'é', hieroglyph: '俄', translate: 'Россия', lesson: 6 },
  { pinyin: 'hái shi', hieroglyph: '还是', translate: 'или', lesson: 6 },
  { pinyin: 'yīng', hieroglyph: '英', translate: 'Англия', lesson: 6 },
  { pinyin: 'dōu', hieroglyph: '都', translate: 'все', lesson: 6 },
  { pinyin: 'zhī', hieroglyph: '只', translate: 'только', lesson: 6 },
  { pinyin: 'tā', hieroglyph: '他', translate: 'он', lesson: 6 },
  { pinyin: 'tā', hieroglyph: '她', translate: 'она', lesson: 6 },
  */
  { pinyin: 'rènshi', hieroglyph: '认识', translate: 'знакомиться', lesson: 2, sound: '2/015.mp3' },
  { pinyin: 'hěn', hieroglyph: '很', translate: 'очень', lesson: 2, sound: '2/016.mp3' },
  { pinyin: 'gāoxìng', hieroglyph: '高兴', translate: 'радостный', lesson: 2, sound: '2/017.mp3' },
  { pinyin: 'zài', hieroglyph: '在', translate: 'в, на', lesson: 2, sound: '2/018.mp3' },
  { pinyin: 'jìnchūkǒu', hieroglyph: '进出口', translate: 'импорт и экспорт', lesson: 2, sound: '2/019.mp3' },
  { pinyin: 'jìnkǒu', hieroglyph: '进口', translate: 'импортировать', lesson: 2, sound: '2/020.mp3' },
  { pinyin: 'chūkǒu', hieroglyph: '出口', translate: 'экспортировать', lesson: 2, sound: '2/021.mp3' },
  { pinyin: 'gōngsī', hieroglyph: '公司', translate: 'компания', lesson: 2, sound: '2/022.mp3' },
  { pinyin: 'gōngzuò', hieroglyph: '工作', translate: 'работа', lesson: 2, sound: '2/023.mp3' },
  { pinyin: 'dà xué', hieroglyph: '大学', translate: 'вуз', lesson: 2, sound: '2/024.mp3' },
  { pinyin: 'xì', hieroglyph: '系', translate: 'факультет', lesson: 2, sound: '2/025.mp3' },
  { pinyin: 'xuéxí', hieroglyph: '学习', translate: 'учиться', lesson: 2, sound: '2/026.mp3' },
  { pinyin: 'kéyǐ', hieroglyph: '可以', translate: 'мочь', lesson: 2, sound: '2/027.mp3' },
  { pinyin: 'gěi', hieroglyph: '给', translate: 'для, в пользу', lesson: 2, sound: '2/028.mp3' },
  { pinyin: 'dǎ diànhuà', hieroglyph: '打电话', translate: 'звонить по телефону', lesson: 2, sound: '2/029.mp3' },
  { pinyin: 'diànhuà', hieroglyph: '电话', translate: 'телефон', lesson: 2, sound: '2/030.mp3' },
  { pinyin: 'wǒde', hieroglyph: '我的', translate: 'мой', lesson: 2, sound: '2/032.mp3' },
  { pinyin: 'wǒmen de', hieroglyph: '我们的', translate: 'наш', lesson: 2, sound: '2/033.mp3' },
  { pinyin: 'hào mǎ', hieroglyph: '号码', translate: 'номер', lesson: 2, sound: '2/034.mp3' },
  { pinyin: 'líng', hieroglyph: '〇', translate: 'ноль', lesson: 2, sound: '2/035.mp3' },
  { pinyin: 'fā', hieroglyph: '发', translate: 'рассылать', lesson: 2, sound: '2/036.mp3' },
  { pinyin: 'diànzǐ yóujiàn', hieroglyph: '电子邮件', translate: 'электронное письмо', lesson: 2, sound: '2/037.mp3' },
  { pinyin: 'diànzǐ', hieroglyph: '电子', translate: 'электроника', lesson: 2, sound: '2/038.mp3' },
  { pinyin: 'yóujiàn', hieroglyph: '邮件', translate: 'почта', lesson: 2, sound: '2/039.mp3' },
  { pinyin: 'zhè', hieroglyph: '这', translate: 'этот', lesson: 2, sound: '2/040.mp3' },
  { pinyin: 'nǚ', hieroglyph: '女', translate: 'женский', lesson: 2, sound: '2/041.mp3' },
  { pinyin: 'péngyou', hieroglyph: '朋友', translate: 'друг', lesson: 2, sound: '2/042.mp3' },
  { pinyin: 'qǐng', hieroglyph: '请', translate: '', lesson: 2, sound: '2/043.mp3' },
  { pinyin: 'jìn', hieroglyph: '进', translate: 'входить', lesson: 2, sound: '2/044.mp3' },
  { pinyin: 'zuò', hieroglyph: '坐', translate: 'входить', lesson: 2, sound: '2/045.mp3' },
  { pinyin: 'xièxie', hieroglyph: '谢谢', translate: 'спасибо', lesson: 2, sound: '2/046.mp3' },
  { pinyin: 'hē', hieroglyph: '喝', translate: 'пить', lesson: 2, sound: '2/047.mp3' },
  { pinyin: 'chá', hieroglyph: '茶', translate: 'чай', lesson: 2, sound: '2/048.mp3' },
  { pinyin: 'nǎr', hieroglyph: '哪儿', translate: 'где', lesson: 2, sound: '2/049.mp3' },
  { pinyin: 'nálǐ', hieroglyph: '哪里', translate: 'где', lesson: 2, sound: '2/050.mp3' },
  { pinyin: 'xuéyuàn', hieroglyph: '学院', translate: 'институт', lesson: 2, sound: '2/051.mp3' },
  { pinyin: 'zěnme yàng', hieroglyph: '怎么样', translate: 'как, каким образом', lesson: 2, sound: '2/052.mp3' },
  { pinyin: 'dà', hieroglyph: '大', translate: 'большой', lesson: 2, sound: '2/053.mp3' },
  { pinyin: 'piàoliang', hieroglyph: '漂亮', translate: 'красивый', lesson: 2, sound: '2/054.mp3' },
  { pinyin: 'xǐhuan', hieroglyph: '喜欢', translate: 'нравиться', lesson: 2, sound: '2/055.mp3' },
  { pinyin: 'nà', hieroglyph: '那', translate: 'тот', lesson: 2, sound: '2/057.mp3' },
  { pinyin: 'nán', hieroglyph: '男', translate: 'мужской', lesson: 2, sound: '2/058.mp3' },
  { pinyin: 'xiǎo', hieroglyph: '小', translate: 'маленький', lesson: 2, sound: '2/059.mp3' },


  { pinyin: 'dìfang', hieroglyph: '地方', translate: 'место', lesson: 3, sound: '3/016.mp3' },
  { pinyin: 'gè', hieroglyph: '个', translate: 'штука, единица', lesson: 3, sound: '3/017.mp3' },
  { pinyin: 'zhèr', hieroglyph: '这儿', translate: 'здесь, тут', lesson: 3, sound: '3/018.mp3' },
  { pinyin: 'zhèli', hieroglyph: '这里', translate: 'здесь, тут', lesson: 3, sound: '3/019.mp3' },
  { pinyin: 'jiā', hieroglyph: '家', translate: 'семья', lesson: 3, sound: '3/020.mp3' },
  { pinyin: 'yǒu', hieroglyph: '有', translate: 'иметь', lesson: 3, sound: '3/021.mp3' },
  { pinyin: 'jǐ', hieroglyph: '几', translate: 'сколько', lesson: 3, sound: '3/022.mp3' },
  { pinyin: 'kǒu', hieroglyph: '口', translate: 'счетное(о людях)', lesson: 3, sound: '3/023.mp3' },
  { pinyin: 'bàba', hieroglyph: '爸爸', translate: 'папа', lesson: 3, sound: '3/024.mp3' },
  { pinyin: 'māma', hieroglyph: '妈妈', translate: 'мама', lesson: 3, sound: '3/025.mp3' },
  { pinyin: 'hé', hieroglyph: '和', translate: 'и', lesson: 3, sound: '3/026.mp3' },
  { pinyin: 'tàitai', hieroglyph: '太太', translate: 'мадам', lesson: 3, sound: '3/027.mp3' },
  { pinyin: 'háizi', hieroglyph: '孩子', translate: 'дети', lesson: 3, sound: '3/028.mp3' },
  { pinyin: 'nánháir', hieroglyph: '男孩', translate: 'мальчик', lesson: 3, sound: '3/029.mp3' },
  { pinyin: 'nǚháir', hieroglyph: '女孩', translate: 'девочка', lesson: 3, sound: '3/030.mp3' },
  { pinyin: 'duō dà', hieroglyph: '多大', translate: 'сколько лет', lesson: 3, sound: '3/031.mp3' },
  { pinyin: 'liǎng', hieroglyph: '两', translate: 'два', lesson: 3, sound: '3/032.mp3' },
  { pinyin: 'suì', hieroglyph: '岁', translate: 'год(о возрасте)', lesson: 3, sound: '3/033.mp3' },
  { pinyin: 'kě ài', hieroglyph: '可爱', translate: 'милый, симпатичный', lesson: 3, sound: '3/034.mp3' },
  { pinyin: 'ba', hieroglyph: '吧', translate: 'равно как русская частица', lesson: 3, sound: '3/035.mp3' },
  { pinyin: 'xuéxiào', hieroglyph: '学校', translate: 'школа, учебное заведение', lesson: 3, sound: '3/036.mp3' },
  { pinyin: 'duōshao', hieroglyph: '多少', translate: 'сколько', lesson: 3, sound: '3/037.mp3' },
  { pinyin: 'xuésheng', hieroglyph: '学生', translate: 'школьник, студент', lesson: 3, sound: '3/038.mp3' },
  { pinyin: 'xiǎng', hieroglyph: '想', translate: 'думать, намеревать', lesson: 3, sound: '3/039.mp3' },
  { pinyin: 'dàgài', hieroglyph: '大概', translate: 'примерно, приблизительно', lesson: 3, sound: '3/040.mp3' },
  { pinyin: 'wàn', hieroglyph: '万', translate: 'десять тысяч', lesson: 3, sound: '3/041.mp3' },
  { pinyin: 'méiyǒu', hieroglyph: '没有', translate: 'не иметь, отсутствовать', lesson: 3, sound: '3/042.mp3' },
  { pinyin: 'duō', hieroglyph: '多', translate: 'многий', lesson: 3, sound: '3/043.mp3' },
  { pinyin: 'qiān', hieroglyph: '千', translate: 'тысяча', lesson: 3, sound: '3/044.mp3' },
  { pinyin: 'qù', hieroglyph: '去', translate: 'идти, ехать', lesson: 3, sound: '3/045.mp3' },
  { pinyin: 'wèi shénme', hieroglyph: '为什么', translate: 'почему, зачем', lesson: 3, sound: '3/046.mp3' },
  { pinyin: 'wèi', hieroglyph: '为', translate: 'для, ради, за', lesson: 3, sound: '3/047.mp3' },
  { pinyin: 'fēn gōngsī', hieroglyph: '分公司', translate: 'филлиал комании', lesson: 3, sound: '3/048.mp3' },
  { pinyin: 'lǎobǎn', hieroglyph: '老板', translate: 'шеф, босс', lesson: 3, sound: '3/049.mp3' },
  { pinyin: 'ràng', hieroglyph: '让', translate: 'просить, велеть', lesson: 3, sound: '3/050.mp3' },
  { pinyin: 'nàr', hieroglyph: '那儿', translate: 'там', lesson: 3, sound: '3/051.mp3' },
  { pinyin: 'nàli', hieroglyph: '那里', translate: 'там', lesson: 3, sound: '3/052.mp3' },
  { pinyin: 'bǎi', hieroglyph: '百', translate: 'сто, сотня', lesson: 3, sound: '3/054.mp3' },
  { pinyin: 'shǎo', hieroglyph: '少', translate: 'немногий', lesson: 3, sound: '3/055.mp3' },
  { pinyin: 'yīnwèi', hieroglyph: '因为', translate: 'потому, что; по причитне того, что', lesson: 3, sound: '3/056.mp3' },


  { pinyin: 'dìtú', hieroglyph: '地​图', translate: 'географическая карта', lesson: 4, sound: '4/012.mp3' },
  { pinyin: 'zhāng', hieroglyph: '张', translate: '(о бумаге, карте, билете..)', lesson: 4, sound: '4/013.mp3' },
  { pinyin: 'Zhōngwén', hieroglyph: '中文', translate: 'китайский язык', lesson: 4, sound: '4/014.mp3' },
  { pinyin: 'éwén', hieroglyph: '俄文', translate: 'русский язык', lesson: 4, sound: '4/015.mp3' },
  { pinyin: 'kàn', hieroglyph: '看', translate: 'смотреть', lesson: 4, sound: '4/016.mp3' },
  { pinyin: 'yíxià', hieroglyph: '一下', translate: 'один раз, чуть-чуть', lesson: 4, sound: '4/017.mp3' },
  { pinyin: 'xíng', hieroglyph: '​行', translate: 'хорошо, ладно, можно', lesson: 4, sound: '4/018.mp3' },
  { pinyin: 'yào', hieroglyph: '要', translate: 'хотеть', lesson: 4, sound: '4/019.mp3' },
  { pinyin: 'gěi', hieroglyph: '​给', translate: 'дать', lesson: 4, sound: '4/020.mp3' },
  { pinyin: 'gàn', hieroglyph: '干', translate: 'делать, совершать', lesson: 4, sound: '4/021.mp3' },
  { pinyin: 'shìde', hieroglyph: '​是​的', translate: 'да, верно', lesson: 4, sound: '4/022.mp3' },
  { pinyin: 'wánr', hieroglyph: '​玩​儿', translate: 'играть', lesson: 4, sound: '4/023.mp3' },
  { pinyin: 'zhīdao', hieroglyph: '知道', translate: 'знать', lesson: 4, sound: '4/024.mp3' },
  { pinyin: 'bǐjiào', hieroglyph: '比​较', translate: 'сравнительно', lesson: 4, sound: '4/025.mp3' },
  { pinyin: 'zhēn', hieroglyph: '​真', translate: 'действительно', lesson: 4, sound: '4/026.mp3' },
  { pinyin: 'yǒu yìsi', hieroglyph: '有意思', translate: 'интересно', lesson: 4, sound: '4/027.mp3' },
  { pinyin: 'yìsi', hieroglyph: 'yisi', translate: 'смысл, интерес', lesson: 4, sound: '4/028.mp3' },
  { pinyin: 'lóng', hieroglyph: '龙', translate: 'дракон', lesson: 4, sound: '4/029.mp3' },
  { pinyin: 'shān', hieroglyph: '山', translate: 'гора', lesson: 4, sound: '4/030.mp3' },
  { pinyin: 'cídiǎn', hieroglyph: '词典', translate: 'словарь', lesson: 4, sound: '4/031.mp3' },
  { pinyin: 'běn', hieroglyph: '本', translate: '(о книге, журнале, ..)', lesson: 4, sound: '4/034.mp3' },
  { pinyin: 'shéi', hieroglyph: '谁', translate: 'кто', lesson: 4, sound: '4/036.mp3' },
  { pinyin: 'qǐng wèn', hieroglyph: '请问', translate: 'позвольте спросить, извините', lesson: 4, sound: '4/037.mp3' },
  { pinyin: 'wèn', hieroglyph: '问', translate: 'спрашивать', lesson: 4, sound: '4/038.mp3' },
  { pinyin: 'duì', hieroglyph: '对', translate: 'правильный, верный', lesson: 4, sound: '4/039.mp3' },
  { pinyin: 'fēicháng', hieroglyph: '非常', translate: 'очень', lesson: 4, sound: '4/040.mp3' },
  { pinyin: 'yǒuyòng', hieroglyph: '有用', translate: 'годный, пригодный, полезный', lesson: 4, sound: '4/041.mp3' },
  { pinyin: 'néng', hieroglyph: '能', translate: 'мочь', lesson: 4, sound: '4/042.mp3' },
  { pinyin: 'yòng', hieroglyph: '用', translate: 'использовать', lesson: 4, sound: '4/043.mp3' },
  { pinyin: 'dāngrán', hieroglyph: '当然', translate: 'конечно, безусловно', lesson: 4, sound: '4/044.mp3' },
  { pinyin: 'shū', hieroglyph: '书', translate: 'книга', lesson: 4, sound: '4/046.mp3' },
  { pinyin: 'běnzi', hieroglyph: '本子', translate: 'тетрадь, блокнот', lesson: 4, sound: '4/047.mp3' },
  { pinyin: 'bǐ', hieroglyph: '笔', translate: 'ручка, карандаш', lesson: 4, sound: '4/048.mp3' },
  { pinyin: 'zhī', hieroglyph: '支', translate: '(о ручке, карандаше,..)', lesson: 4, sound: '4/049.mp3' },

  { pinyin: 'xiǎojiě', hieroglyph: '小姐', translate: 'девушка (обращение к продавщице)', lesson: 5, sound: '5/015.mp3' },
  { pinyin: 'huì', hieroglyph: '会', translate: 'мочь, уметь', lesson: 5, sound: '5/016.mp3' },
  { pinyin: 'yìdiǎnr', hieroglyph: '一点儿', translate: 'немного, чуть-чуть', lesson: 5, sound: '5/017.mp3' },
  { pinyin: 'xiānsheng', hieroglyph: '先生', translate: 'господин', lesson: 5, sound: '5/018.mp3' },
  { pinyin: 'mǎi', hieroglyph: '买', translate: 'покупать', lesson: 5, sound: '5/019.mp3' },
  { pinyin: 'jiàn', hieroglyph: '件', translate: '(о костюме, рубашке)', lesson: 5, sound: '5/020.mp3' },
  { pinyin: 'chènshān', hieroglyph: '衬衫', translate: 'рубашка', lesson: 5, sound: '5/021.mp3' },
  { pinyin: 'bái', hieroglyph: '白', translate: 'белый', lesson: 5, sound: '5/022.mp3' },
  { pinyin: 'qián', hieroglyph: '钱', translate: 'деньги', lesson: 5, sound: '5/023.mp3' },
  { pinyin: 'kuài(yuán)', hieroglyph: '快(元)', translate: '(основая единица китайской валюты)', lesson: 5, sound: '5/024.mp3' },
  { pinyin: 'tài', hieroglyph: '太', translate: 'очень, слишком', lesson: 5, sound: '5/026.mp3' },
  { pinyin: 'guì', hieroglyph: '贵', translate: 'дорогой', lesson: 5, sound: '5/030.mp3' },
  { pinyin: 'hóng', hieroglyph: '红', translate: 'красный', lesson: 5, sound: '5/031.mp3' },
  { pinyin: 'piányi', hieroglyph: '便宜', translate: 'дешёвый', lesson: 5, sound: '5/032.mp3' },
  { pinyin: 'hái', hieroglyph: '还', translate: 'ещё', lesson: 5, sound: '5/033.mp3' },
  { pinyin: 'tiáo', hieroglyph: '条', translate: '(о брюках, дорогах, реках)', lesson: 5, sound: '5/034.mp3' },
  { pinyin: 'kùzi', hieroglyph: '裤子', translate: 'брюки', lesson: 5, sound: '5/035.mp3' },
  { pinyin: 'shì', hieroglyph: '试', translate: 'примерять', lesson: 5, sound: '5/036.mp3' },
  { pinyin: 'nà', hieroglyph: '那', translate: 'тот(та,то,те)', lesson: 5, sound: '5/037.mp3' },
  { pinyin: 'lái', hieroglyph: '来', translate: 'приходить', lesson: 5, sound: '5/038.mp3' },
  { pinyin: 'fàndìàn', hieroglyph: '饭店', translate: 'ресторан', lesson: 5, sound: '5/039.mp3' },
  { pinyin: 'zuì', hieroglyph: '最', translate: 'очень, весьма', lesson: 5, sound: '5/040.mp3' },
  { pinyin: 'hǎochī', hieroglyph: '好吃', translate: 'вкусно', lesson: 5, sound: '5/041.mp3' },
  { pinyin: 'cài', hieroglyph: '菜', translate: 'блюдо', lesson: 5, sound: '5/042.mp3' },
  { pinyin: 'táng cù yú', hieroglyph: '糖醋鱼', translate: 'жаренная рыба в кисло-сладком соусе', lesson: 5, sound: '5/043.mp3' },
  { pinyin: 'táng', hieroglyph: '糖', translate: 'сахар', lesson: 5, sound: '5/044.mp3' },
  { pinyin: 'cù', hieroglyph: '醋', translate: 'уксус', lesson: 5, sound: '5/045.mp3' },
  { pinyin: 'yú', hieroglyph: '鱼', translate: 'рыба', lesson: 5, sound: '5/046.mp3' },
  { pinyin: 'chī', hieroglyph: '吃', translate: 'кушать', lesson: 5, sound: '5/047.mp3' },
  { pinyin: 'là', hieroglyph: '辣', translate: 'острый(о вкусе)', lesson: 5, sound: '5/048.mp3' },
  { pinyin: 'suān là tāng', hieroglyph: '酸辣汤', translate: 'кисло-острый суп', lesson: 5, sound: '5/049.mp3' },
  { pinyin: 'suān', hieroglyph: '酸', translate: 'кислый', lesson: 5, sound: '5/050.mp3' },
  { pinyin: 'tāng', hieroglyph: '汤', translate: 'суп', lesson: 5, sound: '5/051.mp3' },
  { pinyin: 'niúròu', hieroglyph: '牛肉', translate: 'говядина', lesson: 5, sound: '5/052.mp3' },
  { pinyin: 'niú', hieroglyph: '牛', translate: 'бык, корова', lesson: 5, sound: '5/053.mp3' },
  { pinyin: 'ròu', hieroglyph: '肉', translate: 'мясо', lesson: 5, sound: '5/054.mp3' },
  { pinyin: 'hóngshāo', hieroglyph: '红烧', translate: 'тушить (мясо) под соусом', lesson: 5, sound: '5/055.mp3' },
  { pinyin: 'mǐfàn', hieroglyph: '米饭', translate: 'паренный рис', lesson: 5, sound: '5/056.mp3' },
  { pinyin: 'jiǎozi', hieroglyph: '饺子', translate: 'пельмени', lesson: 5, sound: '5/058.mp3' },
  { pinyin: 'píng', hieroglyph: '瓶', translate: 'бутылка', lesson: 5, sound: '5/059.mp3' },
  { pinyin: 'píjiǔ', hieroglyph: '啤酒', translate: 'пиво', lesson: 5, sound: '5/060.mp3' },
  { pinyin: 'děng', hieroglyph: '等', translate: 'ждать', lesson: 5, sound: '5/061.mp3' },
  { pinyin: 'dōngxi', hieroglyph: '东西', translate: 'вещь', lesson: 5, sound: '5/063.mp3' },
  { pinyin: 'mǎi dōngxi', hieroglyph: '买东西', translate: 'покупать, идти за покупками', lesson: 5, sound: '5/064.mp3' },
  { pinyin: 'shāngdiàn', hieroglyph: '商店', translate: 'магазин', lesson: 5, sound: '5/065.mp3' },
  { pinyin: 'mǎi', hieroglyph: '买', translate: 'продавать', lesson: 5, sound: '5/066.mp3' },
  { pinyin: 'yīfu', hieroglyph: '衣服', translate: 'одежда', lesson: 5, sound: '5/067.mp3' },


  { pinyin: 'míngtiān', hieroglyph: '明天', translate: 'завтра', lesson: 6, sound: '6/015.mp3' },
  { pinyin: 'xīngqīliù', hieroglyph: '星期六', translate: 'суббота', lesson: 6, sound: '6/016.mp3' },
  { pinyin: 'xīngqī', hieroglyph: '星期', translate: 'неделя', lesson: 6, sound: '6/017.mp3' },
  { pinyin: 'dǎsuàn', hieroglyph: '打算', translate: 'намереваться, собираться', lesson: 6, sound: '6/018.mp3' },
  { pinyin: 'dǎgōng', hieroglyph: '打工', translate: 'подрабатывать', lesson: 6, sound: '6/019.mp3' },
  { pinyin: 'wǎnshang', hieroglyph: '晚上', translate: 'вечером', lesson: 6, sound: '6/020.mp3' },
  { pinyin: 'yuēhuì', hieroglyph: '约会', translate: 'свидание', lesson: 6, sound: '6/021.mp3' },
  { pinyin: 'báitian', hieroglyph: '白天', translate: 'днём', lesson: 6, sound: '6/022.mp3' },
  { pinyin: 'jiāli', hieroglyph: '家里', translate: 'дома', lesson: 6, sound: '6/023.mp3' },
  { pinyin: 'lǐ', hieroglyph: '里', translate: 'в, во внутрь', lesson: 6, sound: '6/024.mp3' },
  { pinyin: 'xiūxi', hieroglyph: '休息', translate: 'отдыхать', lesson: 6, sound: '6/025.mp3' },
  { pinyin: 'dǎ qiú', hieroglyph: '打球', translate: 'играть в (баскетбол, волейбол, ..)', lesson: 6, sound: '6/026.mp3' },
  { pinyin: 'qiú', hieroglyph: '球', translate: 'мяч', lesson: 6, sound: '6/027.mp3' },
  { pinyin: 'diànshì', hieroglyph: '电视', translate: 'телевидение', lesson: 6, sound: '6/032.mp3' },
  { pinyin: 'wèi', hieroglyph: '位', translate: '(о людях с оттенком вежливости)', lesson: 6, sound: '6/033.mp3' },
  { pinyin: 'shìr', hieroglyph: '事儿', translate: 'дело, дела', lesson: 6, sound: '6/034.mp3' },
  { pinyin: 'kāfēi', hieroglyph: '咖啡', translate: 'кофе', lesson: 6, sound: '6/035.mp3' },
  { pinyin: 'shíhou', hieroglyph: '时候', translate: 'время, время суток', lesson: 6, sound: '6/036.mp3' },
  { pinyin: 'shénme shíhou', hieroglyph: '什么时候', translate: 'какое время, когда', lesson: 6, sound: '6/037.mp3' },
  { pinyin: 'jīntiān', hieroglyph: '今天', translate: 'сегодня', lesson: 6, sound: '6/038.mp3' },
  { pinyin: 'máng', hieroglyph: '忙', translate: 'занятый, занятой', lesson: 6, sound: '6/039.mp3' },
  { pinyin: 'zuò', hieroglyph: '作', translate: 'делать', lesson: 6, sound: '6/040.mp3' },
  { pinyin: 'gōngkè', hieroglyph: '功课', translate: 'урок, домашнее задание', lesson: 6, sound: '6/041.mp3' },
  { pinyin: 'duìbuqǐ', hieroglyph: '对不起', translate: 'извините, прошу прощения', lesson: 6, sound: '6/042.mp3' },
  { pinyin: 'méi guānxi', hieroglyph: '没关系', translate: 'ничего, пожалуйста', lesson: 6, sound: '6/043.mp3' },
  { pinyin: 'kòngr', hieroglyph: '空儿', translate: 'свободное время', lesson: 6, sound: '6/044.mp3' },
  { pinyin: 'diǎn', hieroglyph: '点', translate: 'час', lesson: 6, sound: '6/045.mp3' },
  { pinyin: 'bàn', hieroglyph: '半', translate: 'половина', lesson: 6, sound: '6/047.mp3' },
  { pinyin: 'jiànmiàn', hieroglyph: '见面', translate: 'встречаться', lesson: 6, sound: '6/048.mp3' },
  { pinyin: 'kè', hieroglyph: '刻', translate: 'четверть часа', lesson: 6, sound: '6/049.mp3' },
  { pinyin: 'jiē', hieroglyph: '接', translate: 'идти за кем-л, идти встречать кого-л', lesson: 6, sound: '6/050.mp3' },
  { pinyin: 'zàijiàn', hieroglyph: '再见', translate: 'до свидания', lesson: 6, sound: '6/051.mp3' },
  { pinyin: 'xiànzài', hieroglyph: '现在', translate: 'теперь, сейчас', lesson: 6, sound: '6/053.mp3' },
  { pinyin: 'fēn', hieroglyph: '分', translate: 'минута', lesson: 6, sound: '6/054.mp3' },
  { pinyin: 'zǎoshang', hieroglyph: '早上', translate: 'раннее утро', lesson: 6, sound: '6/055.mp3' },
  { pinyin: 'shàngwǔ', hieroglyph: '上午', translate: 'до полудня, в первой половине дня, утром', lesson: 6, sound: '6/056.mp3' },
  { pinyin: 'xiàwǔ', hieroglyph: '下午', translate: 'вторая половина дня, после полудня, после обеда', lesson: 6, sound: '6/057.mp3' },

  { pinyin: 'fàngjià', hieroglyph: '放假', translate: 'проводить каникулы, идти в отпуск', lesson: 7, sound: '7/013.mp3' },
  { pinyin: 'yuè', hieroglyph: '月', translate: 'месяц', lesson: 7, sound: '7/014.mp3' },
  { pinyin: 'xiàxún', hieroglyph: '下旬', translate: 'третья декада месяца', lesson: 7, sound: '7/015.mp3' },
  { pinyin: 'yǐhòu', hieroglyph: '以后', translate: 'после, потом затем', lesson: 7, sound: '7/016.mp3' },
  { pinyin: 'lǚxíng', hieroglyph: '旅行', translate: 'путешествовать', lesson: 7, sound: '7/017.mp3' },
  { pinyin: 'zhōngxún', hieroglyph: '中旬', translate: 'вторая декада месяца', lesson: 7, sound: '7/018.mp3' },
  { pinyin: 'huòzhě', hieroglyph: '或者', translate: 'или', lesson: 7, sound: '7/019.mp3' },
  { pinyin: 'huílái', hieroglyph: '回来', translate: 'возвращаться', lesson: 7, sound: '7/020.mp3' },
  { pinyin: 'huí', hieroglyph: '回', translate: 'возвращаться', lesson: 7, sound: '7/021.mp3' },
  { pinyin: 'hào', hieroglyph: '号', translate: 'число, день месяца', lesson: 7, sound: '7/022.mp3' },
  { pinyin: 'rì', hieroglyph: '日', translate: 'число, день месяца', lesson: 7, sound: '7/023.mp3' },
  { pinyin: 'yǐqián', hieroglyph: '以前', translate: 'до, прежде, раньше', lesson: 7, sound: '7/024.mp3' },
  { pinyin: 'kěshì', hieroglyph: '可是', translate: 'но, однако', lesson: 7, sound: '7/025.mp3' },
  { pinyin: 'yǒudiǎnr', hieroglyph: '有点儿', translate: 'немножко, чуть', lesson: 7, sound: '7/026.mp3' },
  { pinyin: 'dānxīn', hieroglyph: '担心', translate: 'беспокоиться', lesson: 7, sound: '7/027.mp3' },
  { pinyin: 'bié', hieroglyph: '别', translate: 'не, не надо (делать что-л.)', lesson: 7, sound: '7/028.mp3' },
  { pinyin: 'bāngzhù', hieroglyph: '帮助', translate: 'помогать', lesson: 7, sound: '7/029.mp3' },
  { pinyin: 'jìnlai', hieroglyph: '进来', translate: 'входить', lesson: 7, sound: '7/030.mp3' },
  { pinyin: 'jìn', hieroglyph: '进', translate: 'входить', lesson: 7, sound: '7/031.mp3' },
  { pinyin: 'zhǎo', hieroglyph: '找', translate: 'искать', lesson: 7, sound: '7/032.mp3' },
  { pinyin: 'dài', hieroglyph: '戴', translate: 'надевать(очки, галстук, часы)', lesson: 7, sound: '7/033.mp3' },
  { pinyin: 'fù', hieroglyph: '副', translate: '(об очках, перчатках и тп)', lesson: 7, sound: '7/034.mp3' },
  { pinyin: 'yǎnjìng', hieroglyph: '眼镜', translate: 'очки', lesson: 7, sound: '7/035.mp3' },
  { pinyin: 'měi', hieroglyph: '每', translate: 'каждый', lesson: 7, sound: '7/036.mp3' },
  { pinyin: 'shòu', hieroglyph: '瘦', translate: 'худой, тощий', lesson: 7, sound: '7/037.mp3' },
  { pinyin: 'gāo', hieroglyph: '高', translate: 'высокий', lesson: 7, sound: '7/038.mp3' },
  { pinyin: 'tóufa', hieroglyph: '头发', translate: 'волосы на голове', lesson: 7, sound: '7/039.mp3' },
  { pinyin: 'cháng', hieroglyph: '长', translate: 'длинный, долгий', lesson: 7, sound: '7/040.mp3' },
  { pinyin: 'chuān', hieroglyph: '穿', translate: 'одевать', lesson: 7, sound: '7/041.mp3' },
  { pinyin: 'niúzǎikù', hieroglyph: '牛仔裤', translate: 'джинсы', lesson: 7, sound: '7/042.mp3' },
  { pinyin: 'gāng', hieroglyph: '刚', translate: 'только что, сейчас', lesson: 7, sound: '7/043.mp3' },
  { pinyin: 'chūqù', hieroglyph: '出去', translate: 'выходить', lesson: 7, sound: '7/044.mp3' },
  { pinyin: 'chū', hieroglyph: '出', translate: 'выходить', lesson: 7, sound: '7/045.mp3' },
  { pinyin: 'guò', hieroglyph: '过', translate: 'через', lesson: 7, sound: '7/046.mp3' },
  { pinyin: 'yīhuìr', hieroglyph: '一会儿', translate: 'некоторое время, минутка', lesson: 7, sound: '7/0.47mp3' },
  { pinyin: 'zài', hieroglyph: '再', translate: 'ещё', lesson: 7, sound: '7/048.mp3' },
  { pinyin: 'shàng', hieroglyph: '上', translate: 'на, над, верх, наверх, верхний', lesson: 7, sound: '7/050.mp3' },
  { pinyin: 'xià', hieroglyph: '下', translate: 'под, низ, вниз, нижний', lesson: 7, sound: '7/051.mp3' },
  { pinyin: 'jīnnián', hieroglyph: '今年', translate: 'текущий год', lesson: 7, sound: '7/052.mp3' },
  { pinyin: 'sìchuān', hieroglyph: '四川', translate: 'Сычуань(пров.)', lesson: 7, sound: '7/054.mp3' },
  { pinyin: 'yúnnán', hieroglyph: '云南', translate: 'Юньнань(пров.)', lesson: 7, sound: '7/055.mp3' },

  { pinyin: 'fùjìn', hieroglyph: '附近', translate: 'вблизи, поближе', lesson: 8, sound: '8/015.mp3' },
  { pinyin: 'yínháng', hieroglyph: '银行', translate: 'банк', lesson: 8, sound: '8/016.mp3' },
  { pinyin: 'xíngrén', hieroglyph: '行人', translate: 'пешеход', lesson: 8, sound: '8/017.mp3' },
  { pinyin: 'lí', hieroglyph: '离', translate: 'от.. и до..', lesson: 8, sound: '8/018.mp3' },
  { pinyin: 'yuǎn', hieroglyph: '远', translate: 'далёкий', lesson: 8, sound: '8/019.mp3' },
  { pinyin: 'zěnme', hieroglyph: '怎么', translate: 'как, каким образом', lesson: 8, sound: '8/020.mp3' },
  { pinyin: 'zǒu', hieroglyph: '走', translate: 'идти, ходить', lesson: 8, sound: '8/021.mp3' },
  { pinyin: 'wǎng', hieroglyph: '往', translate: 'в, на (о направлении)', lesson: 8, sound: '8/022.mp3' },
  { pinyin: 'qiánmian', hieroglyph: '前面', translate: 'впереди', lesson: 8, sound: '8/023.mp3' },
  { pinyin: 'qián', hieroglyph: '前', translate: 'перед, впереди', lesson: 8, sound: '8/025.mp3' },
  { pinyin: 'yòumian', hieroglyph: '右面', translate: 'правая сторона', lesson: 8, sound: '8/026.mp3' },
  { pinyin: 'yòu', hieroglyph: '右', translate: 'правый', lesson: 8, sound: '8/028.mp3' },
  { pinyin: 'guǎi', hieroglyph: '拐', translate: 'поворачивать, поворачиваться', lesson: 8, sound: '8/029.mp3' },
  { pinyin: 'mǎlù', hieroglyph: '马路', translate: 'улица', lesson: 8, sound: '8/030.mp3' },
  { pinyin: 'lù', hieroglyph: '路', translate: 'дорога, путь', lesson: 8, sound: '8/031.mp3' },
  { pinyin: 'jiù', hieroglyph: '就', translate: 'вот-вот', lesson: 8, sound: '8/032.mp3' },
  { pinyin: 'yóujú', hieroglyph: '邮局', translate: 'почта', lesson: 8, sound: '8/033.mp3' },
  { pinyin: 'pángbiān', hieroglyph: '旁边', translate: 'рядом, около', lesson: 8, sound: '8/034.mp3' },
  { pinyin: 'bùkèqi', hieroglyph: '不客气', translate: 'не за что, пожалуйста', lesson: 8, sound: '8/035.mp3' },
  { pinyin: 'kèqi', hieroglyph: '客气', translate: 'склонный церемониться', lesson: 8, sound: '8/036.mp3' },
  { pinyin: 'shìzhōngxīn', hieroglyph: '市中心', translate: 'центр города', lesson: 8, sound: '8/037.mp3' },
  { pinyin: 'gàosu', hieroglyph: '告诉', translate: 'говорить, сообщать', lesson: 8, sound: '8/038.mp3' },
  { pinyin: 'dìtiě', hieroglyph: '地铁', translate: 'метро', lesson: 8, sound: '8/039.mp3' },
  { pinyin: 'cóng', hieroglyph: '从', translate: 'с', lesson: 8, sound: '8/040.mp3' },
  { pinyin: 'dào', hieroglyph: '到', translate: 'до', lesson: 8, sound: '8/041.mp3' },
  { pinyin: 'ménkǒu', hieroglyph: '门口', translate: 'ворота, вход, у входа', lesson: 8, sound: '8/042.mp3' },
  { pinyin: 'gōnggòng qìchē', hieroglyph: '公共汽车', translate: 'автобус', lesson: 8, sound: '8/043.mp3' },
  { pinyin: 'qìchē', hieroglyph: '汽车', translate: 'машина, автомобиль', lesson: 8, sound: '8/044.mp3' },
  { pinyin: 'chē', hieroglyph: '车', translate: 'транспортное средство', lesson: 8, sound: '8/045.mp3' },
  { pinyin: 'zhàn', hieroglyph: '站', translate: 'станция, остановка', lesson: 8, sound: '8/046.mp3' },
  { pinyin: 'ránhòu', hieroglyph: '然后', translate: 'потом, затем', lesson: 8, sound: '8/047.mp3' },
  { pinyin: 'huàn', hieroglyph: '换', translate: 'менять, пересаживаться', lesson: 8, sound: '8/048.mp3' },
  { pinyin: 'xiàchē', hieroglyph: '下车', translate: 'сходить с (атобуса)', lesson: 8, sound: '8/049.mp3' },
  { pinyin: 'qí', hieroglyph: '骑', translate: 'ехать на (или верхом)', lesson: 8, sound: '8/050.mp3' },
  { pinyin: 'zìxíngchē', hieroglyph: '自行车', translate: 'велосипед', lesson: 8, sound: '8/051.mp3' },
  { pinyin: 'hòumian', hieroglyph: '后面', translate: 'задняя сторона, позади', lesson: 8, sound: '8/053.mp3' },
  { pinyin: 'zuǒmiàn', hieroglyph: '左面', translate: 'левая сторона, слева', lesson: 8, sound: '8/055.mp3' },
  { pinyin: 'shàngmian', hieroglyph: '上面', translate: 'на, над, наверху', lesson: 8, sound: '8/057.mp3' },
  { pinyin: 'xiàmiàn', hieroglyph: '下面', translate: 'под, внизу', lesson: 8, sound: '8/059.mp3' },
  { pinyin: 'lǐmiàn', hieroglyph: '里面', translate: 'в, внутри', lesson: 8, sound: '8/061.mp3' },
  { pinyin: 'wàimian', hieroglyph: '外面', translate: 'наружная сторона, снаружи', lesson: 8, sound: '8/063.mp3' },
  { pinyin: 'shàng chē', hieroglyph: '上车', translate: 'садится в (машину)', lesson: 8, sound: '8/065.mp3' },
  { pinyin: 'jìn', hieroglyph: '近', translate: 'близкий', lesson: 8, sound: '8/066.mp3' },

  {pinyin: 'chángchéng', hieroglyph: '长城', translate: 'Великая китайская стена', lesson: 9, sound: '9/066.mp3'},
  {pinyin: 'yíhéyuán', hieroglyph: '颐和园', translate: 'парк Ихэюань (Летний сад)', lesson: 9, sound: '9/065.mp3'},
  {pinyin: 'gùgōng', hieroglyph: '故宫', translate: 'музей Гугун (императорский дворец)', lesson: 9, sound: '9/064.mp3'},
  {pinyin: 'pāi zhào', hieroglyph: '拍照', translate: 'фотографировать(ся)', lesson: 9, sound: '9/062.mp3'},
  {pinyin: 'biérén', hieroglyph: '别人', translate: 'другой человек', lesson: 9, sound: '9/061.mp3'},
  {pinyin: 'suǒyǐ', hieroglyph: '所以', translate: 'поэтому', lesson: 9, sound: '9/060.mp3'},
  {pinyin: 'piào', hieroglyph: '票', translate: 'билет', lesson: 9, sound: '9/058.mp3'},
  {pinyin: 'fēijī', hieroglyph: '飞机', translate: 'самолет', lesson: 9, sound: '9/057.mp3'},
  {pinyin: 'fēijīpiào', hieroglyph: '飞机票', translate: 'билет на самолет', lesson: 9, sound: '9/056.mp3'},
  {pinyin: 'děi', hieroglyph: '得', translate: 'надо, следует', lesson: 9, sound: '9/054.mp3'},
  {pinyin: 'péi', hieroglyph: '陪', translate: 'сопровождать', lesson: 9, sound: '9/053.mp3'},
  {pinyin: 'dehua', hieroglyph: '的话', translate: '...если бы', lesson: 9, sound: '9/050.mp3'},
  {pinyin: 'yàoshi', hieroglyph: '要是', translate: 'если бы', lesson: 9, sound: '9/049.mp3'},
  {pinyin: 'huānyíng', hieroglyph: '欢迎', translate: 'приветствовать, добро пожаловать!', lesson: 9, sound: '9/048.mp3'},
  {pinyin: 'biéde', hieroglyph: '别的', translate: 'другой', lesson: 9, sound: '9/047.mp3'},
  {pinyin: 'hǎohàn', hieroglyph: '好汉', translate: 'храбрец, молодец', lesson: 9, sound: '9/046.mp3'},
  {pinyin: 'fēi', hieroglyph: '非', translate: 'не, не являтся', lesson: 9, sound: '9/045.mp3'},
  {pinyin: 'bú dào chángchéng fēi hǎohàn', hieroglyph: '不到长城非好汉', translate: 'кто не поднимался на Великую стену, тот не молодец', lesson: 9, sound: '9/044.mp3'},
  {pinyin: 'dēng', hieroglyph: '登', translate: 'подниматься (на гору), вскарабкиваться', lesson: 9, sound: '9/043.mp3'},
  {pinyin: 'zhàopiàn', hieroglyph: '照片', translate: 'фотография', lesson: 9, sound: '9/042.mp3'},
  {pinyin: 'yìxiē', hieroglyph: '一些', translate: 'некоторые', lesson: 9, sound: '9/041.mp3'},
  {pinyin: 'nǎxiē', hieroglyph: '哪些', translate: 'какие', lesson: 9, sound: '9/040.mp3'},
  {pinyin: 'nàxie', hieroglyph: '那些', translate: 'те', lesson: 9, sound: '9/039.mp3'},
  {pinyin: 'zhèxiē', hieroglyph: '这些', translate: 'эти', lesson: 9, sound: '9/038.mp3'},
  {pinyin: 'shúxī', hieroglyph: '熟悉', translate: 'хорошо знать, быть знакомым с', lesson: 9, sound: '9/034.mp3'},
  {pinyin: 'duì', hieroglyph: '对', translate: 'по отношению к ...', lesson: 9, sound: '9/033.mp3'},
  {pinyin: 'bàn', hieroglyph: '办', translate: 'делать', lesson: 9, sound: '9/032.mp3'},
  {pinyin: 'zìjǐ', hieroglyph: '自己', translate: 'сам, себя', lesson: 9, sound: '9/031.mp3'},
  {pinyin: 'shíjiān', hieroglyph: '时间', translate: 'время', lesson: 9, sound: '9/030.mp3'},
  {pinyin: 'máfan', hieroglyph: '麻烦', translate: 'хлопоты, сталкиваться с трудностями, затруднение', lesson: 9, sound: '9/029.mp3'},
  {pinyin: 'dòngwù', hieroglyph: '动物', translate: 'животное', lesson: 9, sound: '9/028.mp3'},
  {pinyin: 'māo', hieroglyph: '猫', translate: 'кошка', lesson: 9, sound: '9/027.mp3'},
  {pinyin: 'yǒude', hieroglyph: '有的', translate: 'некоторый, кое-кто', lesson: 9, sound: '9/026.mp3'},
  {pinyin: 'chéngshì', hieroglyph: '城市', translate: 'город', lesson: 9, sound: '9/025.mp3'},
  {pinyin: 'tīngshuō', hieroglyph: '听说', translate: 'говорят, что... , знать по слухам', lesson: 9, sound: '9/024.mp3'},
  {pinyin: 'le', hieroglyph: '了', translate: '(для обозначения завершения действия)', lesson: 9, sound: '9/023.mp3'},
  {pinyin: 'dànshì', hieroglyph: '但是', translate: 'но, однако', lesson: 9, sound: '9/022.mp3'},
  {pinyin: 'niǎor', hieroglyph: '鸟儿', translate: 'птичка', lesson: 9, sound: '9/021.mp3'},
  {pinyin: 'huār', hieroglyph: '花儿', translate: 'цветок', lesson: 9, sound: '9/020.mp3'},
  {pinyin: 'guò', hieroglyph: '过', translate: '(для обозначения действия прошедшего времени)', lesson: 9, sound: '9/019.mp3'},
  {pinyin: 'yǎng', hieroglyph: '养', translate: 'держать (животных), выращивать (цветы)', lesson: 9, sound: '9/018.mp3'},
  {pinyin: 'gǒu', hieroglyph: '狗', translate: 'собака', lesson: 9, sound: '9/017.mp3'},
  {pinyin: 'zhī', hieroglyph: '只', translate: '(о маленьких животных - птице, кошке, собаке)', lesson: 9, sound: '9/016.mp3'},
  {pinyin: 'lǎorénjia', hieroglyph: '老人家', translate: 'бабушка, дедушка (вежливое обращение к старцу)', lesson: 9, sound: '9/015.mp3'},

  {pinyin: 'nǐ hái qùguo biéde chéngshìma?', hieroglyph: '你还去别的城市吗？', translate: 'В других городах ты побывал?', lesson: 9, sound: '9/phrases/18.mp3'},
  {pinyin: '"bú dào chángchéng fēi hǎohàn", wǒ zěnme néng bù dēng chángchéng ne?', hieroglyph: '“不到长城非好汉”， 我怎么能不登长城呢？', translate: '"Кто не поднимался на Великую стену, то не молодец". Как же я мог не подниматься на Великую стену?', lesson: 9, sound: '9/phrases/17.mp3'},
  {pinyin: 'nǐ dēngguo chágchéng ma?', hieroglyph: '你等国长城吗？', translate: 'А ты поднимался на Великую стену?', lesson: 9, sound: '9/phrases/16.mp3'},
  {pinyin: 'dangrán. nǐ kàn zhèxiē zhàopiàn. zhè shì gùgōng, zhè shì yíhéyuán...', hieroglyph: '当然。你看这些照片。这是故宫， 这是伊核研院。', translate: 'Конечно. Вот посмотри на эти фотографии. Это музей Гугун, это покр Ихэюань..', lesson: 9, sound: '9/phrases/15.mp3'},
  {pinyin: 'nǐ diù běijīng hěn shúxī le ba?', hieroglyph: '你对北京很熟悉了吧？', translate: 'Ты, наверное, уже хорошо знаешь Пекин?', lesson: 9, sound: '9/phrases/14.mp3'},
  {pinyin: 'shénme shíhou zǒu? xià xīngqīsān.', hieroglyph: '什么时候走。下星期三。', translate: 'Когда отправишься? В следующую среду.', lesson: 9, sound: '9/phrases/13.mp3'},
  {pinyin: 'duì a. gonsī ràng wǒ qù shànghǎi bàn diǎnr shìr.', hieroglyph: '对啊。公司让我去上海办点儿事儿。', translate: 'Да, шеф компании посылает меня в Шанхай по делам.', lesson: 9, sound: '9/phrases/12.mp3'},
  {pinyin: 'tīngshuō, nǐ yào qú shànghǎi le?', hieroglyph: '听说，你要去上海了？', translate: 'Говорят, что ты поедешь в Шанхай?', lesson: 9, sound: '9/phrases/11.mp3'},
  {pinyin: 'yīnwèi wǒ méiyǒu shíjiān, yě méiyǒu qián. wǒ zhǐ néng yǎng wǒ zìjǐ.', hieroglyph: '因为我买有时间，也没有钱。我只能养我自己。', translate: 'Просто у меня нет вреиени, да и денег мало. Я могу прокормить только себя', lesson: 9, sound: '9/phrases/10.mp3'},
  {pinyin: 'wèi shénme? shì bu shì tài máfan?', hieroglyph: '为什么？是不是太麻烦？', translate: 'Почему? Думаете, что много хлопот будет?', lesson: 9, sound: '9/phrases/9.mp3'},
  {pinyin: 'wǒ xǐhuan xiǎo dòngwù, dànshì bù yǎng xiǎo dòngwù', hieroglyph: '我喜欢小动物，但是不养小动物。', translate: 'Мне нравятся маленькие животные, но я их не держую.', lesson: 9, sound: '9/phrases/8.mp3'},
  {pinyin: 'nǐ yě xǐhuan yǎng xiǎo dòngwù?', hieroglyph: '你也喜欢养小动物？', translate: 'Вы тоже любите держать маленьких животных?', lesson: 9, sound: '9/phrases/7.mp3'},
  {pinyin: 'yǒude rén xǐhuan yǎng gǒu, yǒude rén xǐuan yǎng māo, yǒude rén xǐhuan yǎng niǎor, hái yǒude rén xǐhuan yǎng yú...', hieroglyph: '有的人喜欢养狗，有的人喜欢养猫，有的人喜欢养鸟儿，还有的人喜欢养鱼。', translate: 'Одни любят держать собак, другие - кошек, некоторые - птичек, а ещё некоторые - рыбок.', lesson: 9, sound: '9/phrases/6.mp3'},
  {pinyin: 'yǐqián bù xíng, xiànzài kěyǐle.', hieroglyph: '以前不行， 现在可以了。', translate: 'Раньше не позволяли, а теперь можно.', lesson: 9, sound: '9/phrases/5.mp3'},
  {pinyin: 'tīngshuō zài zhōngguó chéngshì li bù néng yǎng gǒu, shìma?', hieroglyph: '听说在中国城市里不能养狗，是吗？', translate: 'Говорят, что в китайских городах нельзя держать собак. Это верно?', lesson: 9, sound: '9/phrases/4.mp3'},
  {pinyin: 'lái zhèr yǐhòu, zhèr de rén dōu xǐhuan yǎng gǒu, wǒ yě yǎng gǒu le.', hieroglyph: '来这儿以后，这儿的人都喜欢养狗， 我也养狗了。', translate: 'После того, как переселился сюда, вижу: здесь все любят держать собак. И я завел себе собачку', lesson: 9, sound: '9/phrases/3.mp3'},
  {pinyin: 'wǒ yǐqián yǎngguo huār, yǎngguo niǎor, dànshì bù xǐhuan yǎng gǒu.', hieroglyph: '我以前养过花儿， 养过鸟儿，但是不养狗。', translate: 'Раньше я выращивал цветы, держал птичек, но не хотел держать собак.', lesson: 9, sound: '9/phrases/2.mp3'},
  {pinyin: 'lǎorénjia, zhè zhī xiǎo gǒu zhēn kěài', hieroglyph: '老人家，这只小狗真可爱', translate: 'Дедушка! Какая у вас симпотичная собачка', lesson: 9, sound: '9/phrases/1.mp3'},

];

export const allLessons = allSamples.reduce<number[]>((xs, x) => {
  if (!xs.includes(x.lesson)) {
    xs.push(x.lesson)
  }
  return xs
}, [])
